### ISSUE TITLE
Manipulating buttons created with decorations

### ISSUE THREAD

**Issue by wjstarrsiii** [georgewalton/Sandals#1]
Just saw this on G+ and it has come in very handy already to make a quick front end to an application I am making.  

One thing I would like to do is manipulate the properties of some buttons based upon other events to enforce a workflow (i.e. disable one button until a prior field has been validated.)  Can this be done? I'm not sure how to access the button properties if it has been created via decoration.

Thanks!

**Comment by georgewalton** [comment]
Hi @wjstarrsiii 

Sorry I've taken so long to get back to you, I haven't checked GitHub in a couple of days.

I don't think it is possible to manipulate a button if it is created via decorator at the moment. (EDIT: Yes it is, please see next comment)

However, since the button class inherits from the TkInter Button class, it's easy to do if you define the button explicitly;

``` python
from sandals import *
try: # python 3
    from tkinter import DISABLED
except ImportError: # python 2
    from Tkinter import DISABLED

with window():
    with flow():
        label("Here's a button:",)
        myButton = button("I'm a button",
            command = lambda: showInfo(message = "Hi"))

    @button("Disable button")
    def disableButton():
        myButton.config(state = DISABLED)
```

I'll have a look tomorrow if there's a way to make it possible to change the properties of buttons defied via decorators, however it might be a bit messy and abuse the **inspect** module a little bit :stuck_out_tongue:

Hope this helps!

**Comment by georgewalton** [comment]
Hi again @wjstarrsiii 

**YES!** It is possible and required a single line to be added to sandals.py, which is embarrassing.

Now, the following should work;

``` python
from sandals import *
try: # python 3
    from tkinter import DISABLED
except ImportError: # python 2
    from Tkinter import DISABLED

with window():
    with flow():
        label("Here's a button:")
        @button("I'm a button")
        def makePopup():
            showInfo(message = "Hi")

    @button("Disable button")
    def disableButton():
        makePopup.button.config(state = DISABLED)
```

The button is now a function attribute of the function it decorates, and so the button can be addressed using `functionName.button`

**Comment by wjstarrsiii** [comment]
That is great!  Don't be embarrassed, I was embarrassed by the obviousness
of your first proposal!

Thanks for the quick response and resolution!

Bill

**Comment by georgewalton** [comment]
Hi @wjstarrsiii
Thanks very much!
I've decided to update sandals.py so that the adjectives for buttons like `DISABLED` are now imported by default, to eliminate the pain of having to import them yourself. I've added the example below (which is now quite short!) to the readme for Sandals as an example of how to address your problem (manipulating buttons defined by decorators);

``` python
from sandals import *
with window():
    @button("This button does nothing")
    def doNothing():
        pass

    @button("Disable button")
    def disableButton():
        doNothing.button.config(state = DISABLED)
```

Thanks for giving me the motivation to actually try and find a solution to this, I'd previously just written it off as impossible :satisfied:
